---
version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  mq:
    image: softwaremill/elasticmq
    volumes:
      - ./elasticmq/elasticmq.conf:/opt/elasticmq.conf
      - ./elasticmq/application.ini:/opt/docker/conf/application.ini
    ports:
      - "9324:9324"
      - "9325:9325"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mq
